# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hkI6Hrj_uw3UbNWUz68wlZRsUfWr7-aJ
"""

#To make changes in the image

import cv2
import numpy as np
img=cv2.imread("/robo1.jpg")

cv2.imshow("hi",img)

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.imwrite("graygr.png",gray)

cv2.imshow("hi2",gray)

thresh=cv2.threshold(gray,185,200,cv2.THRESH_BINARY)[1]

aa=cv2.imwrite("aa.png",thresh)

cv2.imshow("hi",aa)

print(img.size)

print(img.shape)

cv2.imwrite("sample_robo.png",img)

print(img.dtype)

cv2.waitKey(0)

cv2.destroyAllWindows()